name: env_cascade_tabnet
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - cudatoolkit=11.0.221
  - freetype=2.10.4
  - intel-openmp=2021.2.0
  - jpeg=9b
  - lcms2=2.12
  - libedit=3.1.20210216
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openssl=1.0.2u
  - pip=21.1.2
  - python=3.7.0
  - readline=7.0
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - typing_extensions=3.7.4.3
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - APScheduler==3.7.0
    - addict==2.4.0
    - boto3==1.26.79
    - beautifulsoup4==4.9.1
    - chardet==4.0.0
    - click==8.0.1
    - configparser==5.0.2
    - cycler==0.10.0
    - cython==0.29.23
    - config==0.5.1
    - docker-pycreds==0.4.0
    - flask==2.0.1
    - gitdb==4.0.7
    - gitpython==3.1.17
    - gunicorn==20.0.4
    - hvac==1.0.2
    - idna==2.10
    - importlib-metadata==4.5.0
    - itsdangerous==2.0.1
    - jinja2==3.0.1
    - kiwisolver==1.3.1
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - mmdet==2.13.0
    - opencv-python==4.5.2.54
    - pathtools==0.1.2
    - pdf2image==1.15.1
    - pillow==7.0.0
    - promise==2.3
    - protobuf==3.17.3
    - psutil==5.8.0
    - pycocotools==2.0.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pyyaml==5.4.1
    - requests==2.28.2
    - snoop==0.4.3
    - sentry-sdk==1.1.0
    - shortuuid==1.0.1
    - smmap==4.0.0
    - subprocess32==3.5.4
    - terminaltables==3.1.0
    - urllib3==1.26.5
    - wandb==0.10.32
    - werkzeug==2.0.1
    - yapf==0.31.0
    - zipp==3.4.1